import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedDeliveries() async {
  final deliveries = [
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 25, 17, 30)),
      "dropoffAddress": "Suria KLCC, Jalan Ampang, KL",
      "dropoffLocation": const GeoPoint(3.1596, 101.7112),
      "notes": "Fragile, handle with care",
      "partRequesterName": "Alice Tan",
      "partRequesterPhone": "0123456789",
      "partRequesterShop": "Alice Auto Garage",
      "pickupAddress": "Berjaya Times Square, Jalan Imbi, KL",
      "pickupLocation": const GeoPoint(3.1357, 101.7090),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 26, 14, 0)),
      "dropoffAddress": "1 Utama Shopping Centre, Bandar Utama, PJ",
      "dropoffLocation": const GeoPoint(3.1466, 101.6155),
      "notes": "Urgent delivery",
      "partRequesterName": "Bob Lee",
      "partRequesterPhone": "0139876543",
      "partRequesterShop": "Lee Brothers Workshop",
      "pickupAddress": "Low Yat Plaza, Jalan Bukit Bintang, KL",
      "pickupLocation": const GeoPoint(3.1420, 101.7114),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 27, 11, 15)),
      "dropoffAddress": "Sunway Pyramid, Bandar Sunway, PJ",
      "dropoffLocation": const GeoPoint(3.0722, 101.6070),
      "notes": "Customer will pay cash on delivery",
      "partRequesterName": "Charlie Wong",
      "partRequesterPhone": "0191122334",
      "partRequesterShop": "CW Auto Repairs",
      "pickupAddress": "The Mines, Seri Kembangan, Selangor",
      "pickupLocation": const GeoPoint(3.0351, 101.7170),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 27, 16, 45)),
      "dropoffAddress": "IOI City Mall, Putrajaya",
      "dropoffLocation": const GeoPoint(2.9693, 101.7146),
      "notes": "Leave at reception",
      "partRequesterName": "David Lim",
      "partRequesterPhone": "0172223344",
      "partRequesterShop": "DL Motors",
      "pickupAddress": "Sunway Velocity, Cheras, KL",
      "pickupLocation": const GeoPoint(3.1286, 101.7276),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 28, 10, 0)),
      "dropoffAddress": "Setia City Mall, Setia Alam, Shah Alam",
      "dropoffLocation": const GeoPoint(3.1045, 101.4600),
      "notes": "Call before delivery",
      "partRequesterName": "Evelyn Chia",
      "partRequesterPhone": "0185566778",
      "partRequesterShop": "EC Auto Works",
      "pickupAddress": "Paradigm Mall, Kelana Jaya, PJ",
      "pickupLocation": const GeoPoint(3.1121, 101.5947),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 28, 15, 20)),
      "dropoffAddress": "Empire Shopping Gallery, Subang Jaya",
      "dropoffLocation": const GeoPoint(3.0810, 101.5853),
      "notes": "Do not bend package",
      "partRequesterName": "Farah Ali",
      "partRequesterPhone": "0114455667",
      "partRequesterShop": "FA Car Care",
      "pickupAddress": "The Curve, Mutiara Damansara, PJ",
      "pickupLocation": const GeoPoint(3.1569, 101.6115),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 29, 13, 30)),
      "dropoffAddress": "KL Gateway Mall, Bangsar South",
      "dropoffLocation": const GeoPoint(3.1113, 101.6636),
      "notes": "Deliver before lunch",
      "partRequesterName": "Ganesh Kumar",
      "partRequesterPhone": "0147766554",
      "partRequesterShop": "GK Auto Solutions",
      "pickupAddress": "MyTown Shopping Centre, Cheras",
      "pickupLocation": const GeoPoint(3.1362, 101.7297),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 29, 18, 0)),
      "dropoffAddress": "NU Sentral, KL Sentral",
      "dropoffLocation": const GeoPoint(3.1340, 101.6869),
      "notes": "High priority delivery",
      "partRequesterName": "Hafiz Rahman",
      "partRequesterPhone": "0169876543",
      "partRequesterShop": "HR Auto Garage",
      "pickupAddress": "Plaza Damas, Sri Hartamas, KL",
      "pickupLocation": const GeoPoint(3.1658, 101.6537),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 30, 9, 0)),
      "dropoffAddress": "KL East Mall, Wangsa Maju",
      "dropoffLocation": const GeoPoint(3.2110, 101.7580),
      "notes": "Fragile glass inside",
      "partRequesterName": "Ivy Yong",
      "partRequesterPhone": "0126677889",
      "partRequesterShop": "IY Auto Enterprise",
      "pickupAddress": "Lot 10, Bukit Bintang, KL",
      "pickupLocation": const GeoPoint(3.1479, 101.7135),
      "status": "pending",
    },
    {
      "assignedDriverID": "null",
      "createdAt": Timestamp.now(),
      "deliveredAt": Timestamp.fromDate(DateTime(2025, 9, 30, 19, 30)),
      "dropoffAddress": "Publika Shopping Gallery, Solaris Dutamas",
      "dropoffLocation": const GeoPoint(3.1715, 101.6642),
      "notes": "Customer prefers evening delivery",
      "partRequesterName": "Jason Ng",
      "partRequesterPhone": "0192233445",
      "partRequesterShop": "JN Auto Services",
      "pickupAddress": "Starhill Gallery, Bukit Bintang, KL",
      "pickupLocation": const GeoPoint(3.1470, 101.7137),
      "status": "pending",
    },
  ];

  // Save deliveries to Firestore
  for (var i = 0; i < deliveries.length; i++) {
    await FirebaseFirestore.instance
        .collection("deliveries")
        .doc("delivery${(i + 2).toString().padLeft(3, '0')}")
        .set(deliveries[i]);
  }
}
