// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy87fZmAsWV23gx2V2h2mYXpe_HYyyik8',
    appId: '1:308235159417:web:f27d8455bf06991d6bd1a8',
    messagingSenderId: '308235159417',
    projectId: 'parts-delivery-project',
    authDomain: 'parts-delivery-project.firebaseapp.com',
    storageBucket: 'parts-delivery-project.firebasestorage.app',
    measurementId: 'G-HQ94Y1TMCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgDSlmohggtUT-U7_PtrHIOSVnoHlcDHY',
    appId: '1:308235159417:android:a65395059542f9826bd1a8',
    messagingSenderId: '308235159417',
    projectId: 'parts-delivery-project',
    storageBucket: 'parts-delivery-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7N5guaVlgnh4JcnzpXHMwrbIRgs0WN_E',
    appId: '1:308235159417:ios:d4b11be8bac5400f6bd1a8',
    messagingSenderId: '308235159417',
    projectId: 'parts-delivery-project',
    storageBucket: 'parts-delivery-project.firebasestorage.app',
    iosBundleId: 'com.example.practicalAssignmentProject',
  );

}